import type { Order } from "./types";

export const MOCK_ORDERS: Order[] = [
  {
    id: "CF-20481",
    customerName: "Maria Santos",
    customerEmail: "maria@email.com",
    customerPhone: "+63 917 123 4567",
    shop: "Makati Central",
    shopAddress: "Ayala Ave, Makati",
    items: [
      { name: "Caramel Macchiato", qty: 2, price: 370 },
      { name: "Croissant", qty: 1, price: 115 },
    ],
    amount: 485,
    status: "Completed",
    date: "Aug 28, 2026",
    time: "10:42 AM",
    paymentMethod: "Wallet",
    paymentRef: "GC-8821934",
  },
  {
    id: "CF-20480",
    customerName: "James Reyes",
    customerEmail: "james@email.com",
    customerPhone: "+63 918 234 5678",
    shop: "BGC Branch",
    shopAddress: "9th Ave, BGC Taguig",
    items: [{ name: "Cold Brew Classic", qty: 1, price: 165 }],
    amount: 165,
    status: "Pending",
    date: "Aug 28, 2026",
    time: "10:18 AM",
    paymentMethod: "Wallet",
    paymentRef: "WL-3310284",
    extras: "Extra ice please",
  },
  {
    id: "CF-20479",
    customerName: "Ana Cruz",
    customerEmail: "ana.cruz@email.com",
    customerPhone: "+63 919 345 6789",
    shop: "Ortigas Center",
    shopAddress: "Julia Vargas Ave, Pasig",
    items: [
      { name: "Matcha Frappe", qty: 1, price: 190 },
      { name: "Chocolate Cookie", qty: 2, price: 120 },
    ],
    amount: 310,
    status: "Completed",
    date: "Aug 28, 2026",
    time: "09:55 AM",
    paymentMethod: "Card",
    paymentRef: "CD-4412091",
  },
  {
    id: "CF-20478",
    customerName: "Diego Lim",
    customerEmail: "diego@email.com",
    customerPhone: "+63 920 456 7890",
    shop: "Quezon Ave",
    shopAddress: "Quezon Ave, QC",
    items: [
      { name: "Espresso Doppio", qty: 2, price: 240 },
      { name: "Iced Americano", qty: 1, price: 155 },
    ],
    amount: 395,
    status: "Cancelled",
    date: "Aug 27, 2026",
    time: "03:30 PM",
    paymentMethod: "Cash",
    paymentRef: "GC-9912345",
    extras: "Candy",
  },
  {
    id: "CF-20477",
    customerName: "Sofia Mendoza",
    customerEmail: "sofia.m@email.com",
    customerPhone: "+63 921 567 8901",
    shop: "Makati Central",
    shopAddress: "Ayala Ave, Makati",
    items: [{ name: "Vanilla Latte", qty: 1, price: 175 }],
    amount: 175,
    status: "Completed",
    date: "Aug 27, 2026",
    time: "02:15 PM",
    paymentMethod: "Wallet",
    paymentRef: "WL-7721043",
  },
  {
    id: "CF-20476",
    customerName: "Carlo Navarro",
    customerEmail: "carlo.n@email.com",
    customerPhone: "+63 922 678 9012",
    shop: "BGC Branch",
    shopAddress: "9th Ave, BGC Taguig",
    items: [
      { name: "Cappuccino", qty: 2, price: 280 },
      { name: "Blueberry Muffin", qty: 1, price: 95 },
    ],
    amount: 375,
    status: "Processing",
    date: "Aug 27, 2026",
    time: "11:40 AM",
    paymentMethod: "Wallet",
    paymentRef: "WL-6618832",
  },
  {
    id: "CF-20475",
    customerName: "Elena Garcia",
    customerEmail: "elena.g@email.com",
    customerPhone: "+63 923 789 0123",
    shop: "Alabang Town",
    shopAddress: "Alabang-Zapote Rd",
    items: [{ name: "Iced Mocha", qty: 2, price: 340 }],
    amount: 340,
    status: "Completed",
    date: "Aug 26, 2026",
    time: "04:22 PM",
    paymentMethod: "Card",
    paymentRef: "CD-5520198",
  },
  {
    id: "CF-20474",
    customerName: "Miguel Torres",
    customerEmail: "miguel.t@email.com",
    customerPhone: "+63 924 890 1234",
    shop: "Ortigas Center",
    shopAddress: "Julia Vargas Ave, Pasig",
    items: [
      { name: "Americano", qty: 1, price: 145 },
      { name: "Cheese Roll", qty: 1, price: 85 },
    ],
    amount: 230,
    status: "Cancelled",
    date: "Aug 26, 2026",
    time: "01:05 PM",
    paymentMethod: "Cash",
    paymentRef: "CS-3388210",
  },
  {
    id: "CF-20473",
    customerName: "Grace Dela Torre",
    customerEmail: "grace@email.com",
    customerPhone: "+63 925 901 2345",
    shop: "Alabang Town",
    shopAddress: "Alabang-Zapote Rd",
    items: [
      { name: "Vanilla Latte", qty: 2, price: 350 },
      { name: "Banana Bread", qty: 1, price: 115 },
    ],
    amount: 465,
    status: "Processing",
    date: "Aug 25, 2026",
    time: "04:50 PM",
    paymentMethod: "Wallet",
    paymentRef: "WL-5531948",
  },
  {
    id: "CF-20472",
    customerName: "Ryan Villanueva",
    customerEmail: "ryan.v@email.com",
    customerPhone: "+63 926 012 3456",
    shop: "Makati Central",
    shopAddress: "Ayala Ave, Makati",
    items: [{ name: "Flat White", qty: 1, price: 160 }],
    amount: 160,
    status: "Completed",
    date: "Aug 25, 2026",
    time: "09:12 AM",
    paymentMethod: "Wallet",
    paymentRef: "WL-4491022",
  },
];
